#!/bin/bash
# Rubout Example : Embedding Ctrl-H in a string

a="^H^H"        #Two Ctl-H's -- backspaces
echo "abcdefg"  #stdout= abcdefg
echo
echo -n "abcdef$a "   #abcd f
#Space at end    ^         ^ backspaces twice.
echo
echo -n "abcdef$a"    #abcdef
#No space at end
echo; echo

################################################

rubout=^H^H^H^H^H        #   5 x Ctl-H
echo -n "12345678"
sleep 2
echo -n "$rubout"
sleep 2
